spring.application.name=orderingsystem

spring.datasource.url=jdbc:mysql://localhost:3306/orderingsystem?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Cloudinary config
cloudinary.cloud-name=dtuqv5roa
cloudinary.api-key=624888456712292
cloudinary.api-secret=R_CPnmObzwnRhXrDsGDIYf_Cckc
cloudinary.default.product.image.id=template_product_image_vhhm6j
cloudinary.default.product.image.url=https://res.cloudinary.com/dtuqv5roa/image/upload/v1750823733/template_product_image_vhhm6j.jpg

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.cache.redis.time-to-live=300000
